# Generated by Django 4.1 on 2023-11-30 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0003_alter_community_jumlah_direport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.TextField()),
                ('jumlah_like', models.IntegerField(default=0)),
                ('jumlah_dislike', models.IntegerField(default=0)),
                ('jumlah_komen', models.IntegerField(default=0)),
                ('jumlah_direport', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.anggota')),
            ],
        ),
    ]
