# Generated by Django 4.1 on 2023-11-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_community_jumlah_direport'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='daftar_dislike',
            field=models.ManyToManyField(related_name='daftar_dislike', to='community.anggota'),
        ),
        migrations.AddField(
            model_name='post',
            name='daftar_like',
            field=models.ManyToManyField(related_name='daftar_like', to='community.anggota'),
        ),
    ]
