# Generated by Django 4.1 on 2023-12-08 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_community_jumlah_direport'),
        ('post', '0002_post_daftar_dislike_post_daftar_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='community.community'),
            preserve_default=False,
        ),
    ]
