# Generated by Django 4.1 on 2023-11-30 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='post_id',
            new_name='post',
        ),
    ]
