# Generated by Django 4.2.5 on 2023-12-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_anggota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='jumlah_direport',
            field=models.IntegerField(default=0),
        ),
    ]
