# Generated by Django 4.1 on 2023-11-30 03:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_anggota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='jumlah_direport',
            field=models.IntegerField(default=0),
        ),
    ]
