# Generated by Django 4.1 on 2023-11-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_friendrequest_communityinvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='invitation_ptr',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='receiver',
        ),
        migrations.DeleteModel(
            name='CommunityInvitation',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
