# Generated by Django 4.1 on 2023-11-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='invitation_ptr',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
        migrations.DeleteModel(
            name='CommunityInvitation',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
